class PopularStocks:
    """Static class containing popular stock names and their ticker symbols"""

    APPLE = "AAPL"
    MICROSOFT = "MSFT"
    GOOGLE = "GOOGL"
    AMAZON = "AMZN"
    META = "META"
    FACEBOOK = "META" 
    TESLA = "TSLA"
    NETFLIX = "NFLX"
    NVIDIA = "NVDA"
    ORACLE = "ORCL"
    IBM = "IBM"
    INTEL = "INTC"

    #consumer goods
    COCA_COLA = "KO"
    PEPSI = "PEP"
    WALMART = "WMT"
    HOME_DEPOT = "HD"
    NIKE = "NKE"
    MCDONALDS = "MCD"
    STARBUCKS = "SBUX"
    DISNEY = "DIS"