
name: Build and Push Stock Price Assistant Image to AWS ECR # workflow name
on:
  push:
    branches: [ master ] # trigger workflow when pushing to master branch
jobs:
  build-and-push: # Define the main job and its steps
    name: Build and Push to ECR # job name
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials # log in to AWS using secrets
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR 
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # - name: Automatic Tagging of Releases
    #   id: increment-git-tag
    #   run: |
    #     bash ./build/git_update.sh -v major

    - name: Build, Tag, and Push the Image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{env.ECR_REPOSITORY}} # e.g.,
        IMAGE_TAG: latest #${{ steps.increment-git-tag.outputs.git-tag }} 
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
